### ISSUE TITLE
No way to set global admin on a fresh installation

### ISSUE THREAD

**Issue by vmalloc** [platzio/backend#28]
Currently it seems that on a fresh install there is no global admin by default, so this forces a DB fiddling upon fresh installs

**Comment by popen2** [comment]
This can be provided to the chart as an `auth.adminEmails` value (https://github.com/platzio/helm-charts/blob/main/charts/platzio/values.yaml#L15) and in Terraform as the `admin_emails` variable for the main module.

It currently works on the most recent chart/terraform module, so in v0.4.7-beta.X.
